
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassLibrary1
{

using System;
    using System.Collections.Generic;
    
public partial class LogHistDateOrder_HB
{

    public int Id { get; set; }

    public int OrderId { get; set; }

    public System.DateTime DateOrder { get; set; }

    public decimal Summa { get; set; }

}

}
