//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogHistDateOrder_HB
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public System.DateTime DateOrder { get; set; }
        public decimal Summa { get; set; }
    }
}
