

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassLibrary1
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class MarketEntities : DbContext
{
    public MarketEntities()
        : base("name=MarketEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Categories_HB> Categories_HB { get; set; }

    public virtual DbSet<LogHistDateOrder_HB> LogHistDateOrder_HB { get; set; }

    public virtual DbSet<Orders_HB> Orders_HB { get; set; }

    public virtual DbSet<Users_HB> Users_HB { get; set; }

}

}

